quarkus:
  http:
    cors.enabled: true
    cors.origins: "*"
    cors.methods: "GET,POST,PUT,DELETE,OPTIONS"
    cors.headers: "accept,authorization,content-type"
    cors.exposed-headers: "location"
  rest-client:
    external-api:
      url:
        - "${external-api.url}"
  datasource:
    db-kind: postgresql
    devservices:
      enabled: true
      reuse: false
      image-name: "postgres"
      container-env:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      port: 5432
      volumes:
        - "db/init-db:/docker-entrypoint-initdb.d"
    db-name: "postgres"
    username: "postgres"
    password: "postgres"
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
      initial-size: 2
      min-size: 2
      max-size: 5
  liquibase:
    migrate-at-start: true
    search-path:
      - "src/main/resources/db"
    change-log: "changelog.xml"
  hibernate-orm:
    packages: com.ctw.workstation
    validate-in-dev-mode: false
    database:
      generation: none
    log:
      sql: ${hibernate_orm_log_sql:false}

external-api:
  url:
    - "http://localhost:3001"