name: Java CI with Maven
env:
  docker_image_name : 'academy'
  docker_tag_name : ''
  artifact_name : "artifact_name"
  docker_path : "src/main/docker/Dockerfile.jvm"
  artifact_path : "artifact_name"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        uses: ./.github/actions/maven_build

      - name: Build Docker image
        uses: ./.github/actions/docker_build
        with:
          path_dockerfile: "${{env.docker_path}}"
          image_name: docker_image_name
          tag_name: docker_tag_name
      - name: Docker save
        run: docker save -o ${{env.docker_image_name}}.tar ${{image_name}}:${{tag_name}}

      - run: mkdir -p path
      - uses: actions/upload-artifact@v4
        with:
          name: "${{env.artifact_name}}"
          path: "${{env.docker_image_name}}.tar"


  Outracena:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List Docker images
        run: docker image ls



